# Generated by Django 5.1.1 on 2025-01-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0002_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('time', models.TimeField()),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
