# Generated by Django 5.1.1 on 2025-01-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='Bookings',
        ),
    ]
